name: test_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # flutter_google_places: ^0.3.0
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.0.4
  geolocator: ^8.2.1
  google_maps_flutter: ^2.1.5
  # google_places_flutter: ^2.0.5
  flutter_google_places_hoc081098: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
  uses-material-design: true
